# This is a TOML document. Boom
[discovery]
    nodes = ["127.0.0.1:7171"]

[regions]
    "bj" = ["北京","天津","河北","山东","山西","内蒙古","辽宁","吉林","黑龙江","甘肃","宁夏","新疆"]
    "sh" = ["上海","江苏","浙江","安徽","江西","湖北","重庆","陕西","青海","河南","台湾"]
    "gz" = ["广东","福建","广西","海南","湖南","四川","贵州","云南","西藏","香港","澳门"]
    
[node]
    defaultDomain = "conn.goim.io"
    hostDomain = ".goim.io"
    heartbeat = "4m"
    heartbeatMax = 2
    tcpPort = 3101
    wsPort = 3102
    wssPort = 3103
    regionWeight = 1.6

[backoff]
    maxDelay = 300
    baseDelay = 3
    factor = 1.8
    jitter = 0.3

[rpcServer]
    network = "tcp"
    addr = ":3119"
    timeout = "1s"

[rpcClient]
    dial = "1s"
    timeout = "1s"

[httpServer]
    network = "tcp"
    addr = ":3111"
	readTimeout = "1s"
	writeTimeout = "1s"

[kafka]
    topic = "goim-push-topic"
    brokers = ["127.0.0.1:9092"]

[redis]
    network = "tcp"
    addr = "127.0.0.1:6379"
    active = 60000
    idle = 1024
    dialTimeout = "200ms"
    readTimeout = "500ms"
    writeTimeout = "500ms"
    idleTimeout = "120s"
    expire = "30m"
